name: work_calendar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  derry: ^1.5.0
  dartz: ^0.10.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  injectable: ^2.3.2
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  collection: ^1.18.0
  path_provider: ^2.1.1
  flutter_svg: ^2.0.9
  
  #router
  auto_route: ^7.8.4

  #localization
  easy_localization: ^3.0.3

  #logger
  logger: ^2.0.2+1

  #API
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/langs/

#scripts
scripts: derry.yaml